package sep3.via.delivery_app;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

public final class Grpc {
  private Grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PackageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code PackageRequest}
   */
  public  static final class PackageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PackageRequest)
      PackageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageRequest.newBuilder() to construct.
    private PackageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Grpc.internal_static_PackageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Grpc.internal_static_PackageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Grpc.PackageRequest.class, Grpc.PackageRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Grpc.PackageRequest)) {
        return super.equals(obj);
      }
      Grpc.PackageRequest other = (Grpc.PackageRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Grpc.PackageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.PackageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.PackageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Grpc.PackageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.PackageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.PackageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Grpc.PackageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PackageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PackageRequest)
        Grpc.PackageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Grpc.internal_static_PackageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Grpc.internal_static_PackageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Grpc.PackageRequest.class, Grpc.PackageRequest.Builder.class);
      }

      // Construct using sep4.via.delivery_app.Grpc.PackageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Grpc.internal_static_PackageRequest_descriptor;
      }

      @java.lang.Override
      public Grpc.PackageRequest getDefaultInstanceForType() {
        return Grpc.PackageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Grpc.PackageRequest build() {
        Grpc.PackageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Grpc.PackageRequest buildPartial() {
        Grpc.PackageRequest result = new Grpc.PackageRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Grpc.PackageRequest) {
          return mergeFrom((Grpc.PackageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Grpc.PackageRequest other) {
        if (other == Grpc.PackageRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Grpc.PackageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Grpc.PackageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PackageRequest)
    }

    // @@protoc_insertion_point(class_scope:PackageRequest)
    private static final Grpc.PackageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Grpc.PackageRequest();
    }

    public static Grpc.PackageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageRequest>
        PARSER = new com.google.protobuf.AbstractParser<PackageRequest>() {
      @java.lang.Override
      public PackageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Grpc.PackageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageGetDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PackageGetDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 senderId = 1;</code>
     * @return The senderId.
     */
    long getSenderId();

    /**
     * <code>double weight = 2;</code>
     * @return The weight.
     */
    double getWeight();

    /**
     * <code>int64 id = 3;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string senderName = 5;</code>
     * @return The senderName.
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 5;</code>
     * @return The bytes for senderName.
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string receiverName = 6;</code>
     * @return The receiverName.
     */
    java.lang.String getReceiverName();
    /**
     * <code>string receiverName = 6;</code>
     * @return The bytes for receiverName.
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     * @return Whether the receiverAddress field is set.
     */
    boolean hasReceiverAddress();
    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     * @return The receiverAddress.
     */
    Grpc.AddressGetDTO getReceiverAddress();
    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     */
    Grpc.AddressGetDTOOrBuilder getReceiverAddressOrBuilder();
  }
  /**
   * Protobuf type {@code PackageGetDTO}
   */
  public  static final class PackageGetDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PackageGetDTO)
      PackageGetDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageGetDTO.newBuilder() to construct.
    private PackageGetDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageGetDTO() {
      status_ = "";
      senderName_ = "";
      receiverName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageGetDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageGetDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              senderId_ = input.readInt64();
              break;
            }
            case 17: {

              weight_ = input.readDouble();
              break;
            }
            case 24: {

              id_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 58: {
              Grpc.AddressGetDTO.Builder subBuilder = null;
              if (receiverAddress_ != null) {
                subBuilder = receiverAddress_.toBuilder();
              }
              receiverAddress_ = input.readMessage(Grpc.AddressGetDTO.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiverAddress_);
                receiverAddress_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Grpc.internal_static_PackageGetDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Grpc.internal_static_PackageGetDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Grpc.PackageGetDTO.class, Grpc.PackageGetDTO.Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    private long senderId_;
    /**
     * <code>int64 senderId = 1;</code>
     * @return The senderId.
     */
    public long getSenderId() {
      return senderId_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 2;
    private double weight_;
    /**
     * <code>double weight = 2;</code>
     * @return The weight.
     */
    public double getWeight() {
      return weight_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private long id_;
    /**
     * <code>int64 id = 3;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 5;</code>
     * @return The senderName.
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 5;</code>
     * @return The bytes for senderName.
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>string receiverName = 6;</code>
     * @return The receiverName.
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverName = 6;</code>
     * @return The bytes for receiverName.
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERADDRESS_FIELD_NUMBER = 7;
    private Grpc.AddressGetDTO receiverAddress_;
    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     * @return Whether the receiverAddress field is set.
     */
    public boolean hasReceiverAddress() {
      return receiverAddress_ != null;
    }
    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     * @return The receiverAddress.
     */
    public Grpc.AddressGetDTO getReceiverAddress() {
      return receiverAddress_ == null ? Grpc.AddressGetDTO.getDefaultInstance() : receiverAddress_;
    }
    /**
     * <code>.AddressGetDTO receiverAddress = 7;</code>
     */
    public Grpc.AddressGetDTOOrBuilder getReceiverAddressOrBuilder() {
      return getReceiverAddress();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderId_ != 0L) {
        output.writeInt64(1, senderId_);
      }
      if (weight_ != 0D) {
        output.writeDouble(2, weight_);
      }
      if (id_ != 0L) {
        output.writeInt64(3, id_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, receiverName_);
      }
      if (receiverAddress_ != null) {
        output.writeMessage(7, getReceiverAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, senderId_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, weight_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, id_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, receiverName_);
      }
      if (receiverAddress_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getReceiverAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Grpc.PackageGetDTO)) {
        return super.equals(obj);
      }
      Grpc.PackageGetDTO other = (Grpc.PackageGetDTO) obj;

      if (getSenderId()
          != other.getSenderId()) return false;
      if (java.lang.Double.doubleToLongBits(getWeight())
          != java.lang.Double.doubleToLongBits(
              other.getWeight())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getSenderName()
          .equals(other.getSenderName())) return false;
      if (!getReceiverName()
          .equals(other.getReceiverName())) return false;
      if (hasReceiverAddress() != other.hasReceiverAddress()) return false;
      if (hasReceiverAddress()) {
        if (!getReceiverAddress()
            .equals(other.getReceiverAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderId());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      if (hasReceiverAddress()) {
        hash = (37 * hash) + RECEIVERADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getReceiverAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Grpc.PackageGetDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageGetDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageGetDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageGetDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageGetDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.PackageGetDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.PackageGetDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.PackageGetDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.PackageGetDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Grpc.PackageGetDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.PackageGetDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.PackageGetDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Grpc.PackageGetDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PackageGetDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PackageGetDTO)
        Grpc.PackageGetDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Grpc.internal_static_PackageGetDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Grpc.internal_static_PackageGetDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Grpc.PackageGetDTO.class, Grpc.PackageGetDTO.Builder.class);
      }

      // Construct using sep4.via.delivery_app.Grpc.PackageGetDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderId_ = 0L;

        weight_ = 0D;

        id_ = 0L;

        status_ = "";

        senderName_ = "";

        receiverName_ = "";

        if (receiverAddressBuilder_ == null) {
          receiverAddress_ = null;
        } else {
          receiverAddress_ = null;
          receiverAddressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Grpc.internal_static_PackageGetDTO_descriptor;
      }

      @java.lang.Override
      public Grpc.PackageGetDTO getDefaultInstanceForType() {
        return Grpc.PackageGetDTO.getDefaultInstance();
      }

      @java.lang.Override
      public Grpc.PackageGetDTO build() {
        Grpc.PackageGetDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Grpc.PackageGetDTO buildPartial() {
        Grpc.PackageGetDTO result = new Grpc.PackageGetDTO(this);
        result.senderId_ = senderId_;
        result.weight_ = weight_;
        result.id_ = id_;
        result.status_ = status_;
        result.senderName_ = senderName_;
        result.receiverName_ = receiverName_;
        if (receiverAddressBuilder_ == null) {
          result.receiverAddress_ = receiverAddress_;
        } else {
          result.receiverAddress_ = receiverAddressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Grpc.PackageGetDTO) {
          return mergeFrom((Grpc.PackageGetDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Grpc.PackageGetDTO other) {
        if (other == Grpc.PackageGetDTO.getDefaultInstance()) return this;
        if (other.getSenderId() != 0L) {
          setSenderId(other.getSenderId());
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (other.hasReceiverAddress()) {
          mergeReceiverAddress(other.getReceiverAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Grpc.PackageGetDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Grpc.PackageGetDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long senderId_ ;
      /**
       * <code>int64 senderId = 1;</code>
       * @return The senderId.
       */
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <code>int64 senderId = 1;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(long value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 senderId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        
        senderId_ = 0L;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 2;</code>
       * @return The weight.
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 2;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 3;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 4;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 5;</code>
       * @return The senderName.
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 5;</code>
       * @return The bytes for senderName.
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 5;</code>
       * @param value The senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 5;</code>
       * @param value The bytes for senderName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>string receiverName = 6;</code>
       * @return The receiverName.
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverName = 6;</code>
       * @return The bytes for receiverName.
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverName = 6;</code>
       * @param value The receiverName to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 6;</code>
       * @param value The bytes for receiverName to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private Grpc.AddressGetDTO receiverAddress_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Grpc.AddressGetDTO, Grpc.AddressGetDTO.Builder, Grpc.AddressGetDTOOrBuilder> receiverAddressBuilder_;
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       * @return Whether the receiverAddress field is set.
       */
      public boolean hasReceiverAddress() {
        return receiverAddressBuilder_ != null || receiverAddress_ != null;
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       * @return The receiverAddress.
       */
      public Grpc.AddressGetDTO getReceiverAddress() {
        if (receiverAddressBuilder_ == null) {
          return receiverAddress_ == null ? Grpc.AddressGetDTO.getDefaultInstance() : receiverAddress_;
        } else {
          return receiverAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Builder setReceiverAddress(Grpc.AddressGetDTO value) {
        if (receiverAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiverAddress_ = value;
          onChanged();
        } else {
          receiverAddressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Builder setReceiverAddress(
          Grpc.AddressGetDTO.Builder builderForValue) {
        if (receiverAddressBuilder_ == null) {
          receiverAddress_ = builderForValue.build();
          onChanged();
        } else {
          receiverAddressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Builder mergeReceiverAddress(Grpc.AddressGetDTO value) {
        if (receiverAddressBuilder_ == null) {
          if (receiverAddress_ != null) {
            receiverAddress_ =
              Grpc.AddressGetDTO.newBuilder(receiverAddress_).mergeFrom(value).buildPartial();
          } else {
            receiverAddress_ = value;
          }
          onChanged();
        } else {
          receiverAddressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Builder clearReceiverAddress() {
        if (receiverAddressBuilder_ == null) {
          receiverAddress_ = null;
          onChanged();
        } else {
          receiverAddress_ = null;
          receiverAddressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Grpc.AddressGetDTO.Builder getReceiverAddressBuilder() {
        
        onChanged();
        return getReceiverAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      public Grpc.AddressGetDTOOrBuilder getReceiverAddressOrBuilder() {
        if (receiverAddressBuilder_ != null) {
          return receiverAddressBuilder_.getMessageOrBuilder();
        } else {
          return receiverAddress_ == null ?
              Grpc.AddressGetDTO.getDefaultInstance() : receiverAddress_;
        }
      }
      /**
       * <code>.AddressGetDTO receiverAddress = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Grpc.AddressGetDTO, Grpc.AddressGetDTO.Builder, Grpc.AddressGetDTOOrBuilder> 
          getReceiverAddressFieldBuilder() {
        if (receiverAddressBuilder_ == null) {
          receiverAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Grpc.AddressGetDTO, Grpc.AddressGetDTO.Builder, Grpc.AddressGetDTOOrBuilder>(
                  getReceiverAddress(),
                  getParentForChildren(),
                  isClean());
          receiverAddress_ = null;
        }
        return receiverAddressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PackageGetDTO)
    }

    // @@protoc_insertion_point(class_scope:PackageGetDTO)
    private static final Grpc.PackageGetDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Grpc.PackageGetDTO();
    }

    public static Grpc.PackageGetDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageGetDTO>
        PARSER = new com.google.protobuf.AbstractParser<PackageGetDTO>() {
      @java.lang.Override
      public PackageGetDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageGetDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageGetDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageGetDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Grpc.PackageGetDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressGetDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressGetDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string street = 2;</code>
     * @return The street.
     */
    java.lang.String getStreet();
    /**
     * <code>string street = 2;</code>
     * @return The bytes for street.
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string zipCode = 5;</code>
     * @return The zipCode.
     */
    java.lang.String getZipCode();
    /**
     * <code>string zipCode = 5;</code>
     * @return The bytes for zipCode.
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();
  }
  /**
   * Protobuf type {@code AddressGetDTO}
   */
  public  static final class AddressGetDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddressGetDTO)
      AddressGetDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddressGetDTO.newBuilder() to construct.
    private AddressGetDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressGetDTO() {
      street_ = "";
      city_ = "";
      zipCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddressGetDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddressGetDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              street_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              zipCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Grpc.internal_static_AddressGetDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Grpc.internal_static_AddressGetDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Grpc.AddressGetDTO.class, Grpc.AddressGetDTO.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int STREET_FIELD_NUMBER = 2;
    private volatile java.lang.Object street_;
    /**
     * <code>string street = 2;</code>
     * @return The street.
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>string street = 2;</code>
     * @return The bytes for street.
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 3;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIPCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object zipCode_;
    /**
     * <code>string zipCode = 5;</code>
     * @return The zipCode.
     */
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      }
    }
    /**
     * <code>string zipCode = 5;</code>
     * @return The bytes for zipCode.
     */
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getStreetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, street_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, zipCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getStreetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, street_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, zipCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Grpc.AddressGetDTO)) {
        return super.equals(obj);
      }
      Grpc.AddressGetDTO other = (Grpc.AddressGetDTO) obj;

      if (getId()
          != other.getId()) return false;
      if (!getStreet()
          .equals(other.getStreet())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getZipCode()
          .equals(other.getZipCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getZipCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Grpc.AddressGetDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.AddressGetDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.AddressGetDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.AddressGetDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.AddressGetDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Grpc.AddressGetDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Grpc.AddressGetDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.AddressGetDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.AddressGetDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Grpc.AddressGetDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Grpc.AddressGetDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Grpc.AddressGetDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Grpc.AddressGetDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressGetDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressGetDTO)
        Grpc.AddressGetDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Grpc.internal_static_AddressGetDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Grpc.internal_static_AddressGetDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Grpc.AddressGetDTO.class, Grpc.AddressGetDTO.Builder.class);
      }

      // Construct using sep4.via.delivery_app.Grpc.AddressGetDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        street_ = "";

        city_ = "";

        zipCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Grpc.internal_static_AddressGetDTO_descriptor;
      }

      @java.lang.Override
      public Grpc.AddressGetDTO getDefaultInstanceForType() {
        return Grpc.AddressGetDTO.getDefaultInstance();
      }

      @java.lang.Override
      public Grpc.AddressGetDTO build() {
        Grpc.AddressGetDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Grpc.AddressGetDTO buildPartial() {
        Grpc.AddressGetDTO result = new Grpc.AddressGetDTO(this);
        result.id_ = id_;
        result.street_ = street_;
        result.city_ = city_;
        result.zipCode_ = zipCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Grpc.AddressGetDTO) {
          return mergeFrom((Grpc.AddressGetDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Grpc.AddressGetDTO other) {
        if (other == Grpc.AddressGetDTO.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getZipCode().isEmpty()) {
          zipCode_ = other.zipCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Grpc.AddressGetDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Grpc.AddressGetDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object street_ = "";
      /**
       * <code>string street = 2;</code>
       * @return The street.
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street = 2;</code>
       * @return The bytes for street.
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street = 2;</code>
       * @param value The street to set.
       * @return This builder for chaining.
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        street_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string street = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreet() {
        
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      /**
       * <code>string street = 2;</code>
       * @param value The bytes for street to set.
       * @return This builder for chaining.
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        street_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 3;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 3;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 3;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>string zipCode = 5;</code>
       * @return The zipCode.
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zipCode = 5;</code>
       * @return The bytes for zipCode.
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zipCode = 5;</code>
       * @param value The zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zipCode = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearZipCode() {
        
        zipCode_ = getDefaultInstance().getZipCode();
        onChanged();
        return this;
      }
      /**
       * <code>string zipCode = 5;</code>
       * @param value The bytes for zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zipCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddressGetDTO)
    }

    // @@protoc_insertion_point(class_scope:AddressGetDTO)
    private static final Grpc.AddressGetDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Grpc.AddressGetDTO();
    }

    public static Grpc.AddressGetDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressGetDTO>
        PARSER = new com.google.protobuf.AbstractParser<AddressGetDTO>() {
      @java.lang.Override
      public AddressGetDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressGetDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressGetDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressGetDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Grpc.AddressGetDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PackageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageGetDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PackageGetDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressGetDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressGetDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\"\034\n\016PackageRequest\022\n\n\002id\030\001 \001" +
      "(\003\"\240\001\n\rPackageGetDTO\022\020\n\010senderId\030\001 \001(\003\022\016" +
      "\n\006weight\030\002 \001(\001\022\n\n\002id\030\003 \001(\003\022\016\n\006status\030\004 \001" +
      "(\t\022\022\n\nsenderName\030\005 \001(\t\022\024\n\014receiverName\030\006" +
      " \001(\t\022\'\n\017receiverAddress\030\007 \001(\0132\016.AddressG" +
      "etDTO\"J\n\rAddressGetDTO\022\n\n\002id\030\001 \001(\003\022\016\n\006st" +
      "reet\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022\017\n\007zipCode\030\005 \001(" +
      "\t28\n\007Package\022-\n\ngetPackage\022\017.PackageRequ" +
      "est\032\016.PackageGetDTOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PackageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PackageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PackageRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PackageGetDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PackageGetDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PackageGetDTO_descriptor,
        new java.lang.String[] { "SenderId", "Weight", "Id", "Status", "SenderName", "ReceiverName", "ReceiverAddress", });
    internal_static_AddressGetDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddressGetDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressGetDTO_descriptor,
        new java.lang.String[] { "Id", "Street", "City", "ZipCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
